/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as _layoutRouteImport } from './routes/__layout'
import { Route as _layoutIndexRouteImport } from './routes/__layout/index'
import { Route as _layoutSearchRouteImport } from './routes/__layout/search'
import { Route as _layoutInsightsRouteImport } from './routes/__layout/insights'
import { Route as _layoutGameRouteImport } from './routes/__layout/game'
import { Route as _layoutChatRouteImport } from './routes/__layout/chat'
import { Route as _layoutAboutRouteImport } from './routes/__layout/about'
import { Route as _layoutActivytyIndexRouteImport } from './routes/__layout/activyty/index'
import { Route as _layoutUserName_layoutRouteImport } from './routes/__layout/$userName/__layout'
import { Route as _layoutActivytyFollowsIndexRouteImport } from './routes/__layout/activyty/follows/index'
import { Route as _layoutUserName_layoutIndexRouteImport } from './routes/__layout/$userName/__layout/index'
import { Route as _layoutUserNamePostPostIdRouteImport } from './routes/__layout/$userName/post/$postId'
import { Route as _layoutUserName_layoutRepostsIndexRouteImport } from './routes/__layout/$userName/__layout/reposts/index'
import { Route as _layoutUserName_layoutRepliesIndexRouteImport } from './routes/__layout/$userName/__layout/replies/index'
import { Route as _layoutUserName_layoutMediaIndexRouteImport } from './routes/__layout/$userName/__layout/media/index'

const _layoutUserNameRouteImport = createFileRoute('/__layout/$userName')()

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutRoute = _layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutUserNameRoute = _layoutUserNameRouteImport.update({
  id: '/$userName',
  path: '/$userName',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutIndexRoute = _layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutSearchRoute = _layoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutInsightsRoute = _layoutInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutGameRoute = _layoutGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutChatRoute = _layoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutAboutRoute = _layoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutActivytyIndexRoute = _layoutActivytyIndexRouteImport.update({
  id: '/activyty/',
  path: '/activyty/',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutUserName_layoutRoute = _layoutUserName_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => _layoutUserNameRoute,
} as any)
const _layoutActivytyFollowsIndexRoute =
  _layoutActivytyFollowsIndexRouteImport.update({
    id: '/activyty/follows/',
    path: '/activyty/follows/',
    getParentRoute: () => _layoutRoute,
  } as any)
const _layoutUserName_layoutIndexRoute =
  _layoutUserName_layoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _layoutUserName_layoutRoute,
  } as any)
const _layoutUserNamePostPostIdRoute =
  _layoutUserNamePostPostIdRouteImport.update({
    id: '/post/$postId',
    path: '/post/$postId',
    getParentRoute: () => _layoutUserNameRoute,
  } as any)
const _layoutUserName_layoutRepostsIndexRoute =
  _layoutUserName_layoutRepostsIndexRouteImport.update({
    id: '/reposts/',
    path: '/reposts/',
    getParentRoute: () => _layoutUserName_layoutRoute,
  } as any)
const _layoutUserName_layoutRepliesIndexRoute =
  _layoutUserName_layoutRepliesIndexRouteImport.update({
    id: '/replies/',
    path: '/replies/',
    getParentRoute: () => _layoutUserName_layoutRoute,
  } as any)
const _layoutUserName_layoutMediaIndexRoute =
  _layoutUserName_layoutMediaIndexRouteImport.update({
    id: '/media/',
    path: '/media/',
    getParentRoute: () => _layoutUserName_layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/about': typeof _layoutAboutRoute
  '/chat': typeof _layoutChatRoute
  '/game': typeof _layoutGameRoute
  '/insights': typeof _layoutInsightsRoute
  '/search': typeof _layoutSearchRoute
  '/': typeof _layoutIndexRoute
  '/$userName': typeof _layoutUserName_layoutRouteWithChildren
  '/activyty': typeof _layoutActivytyIndexRoute
  '/$userName/post/$postId': typeof _layoutUserNamePostPostIdRoute
  '/$userName/': typeof _layoutUserName_layoutIndexRoute
  '/activyty/follows': typeof _layoutActivytyFollowsIndexRoute
  '/$userName/media': typeof _layoutUserName_layoutMediaIndexRoute
  '/$userName/replies': typeof _layoutUserName_layoutRepliesIndexRoute
  '/$userName/reposts': typeof _layoutUserName_layoutRepostsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/about': typeof _layoutAboutRoute
  '/chat': typeof _layoutChatRoute
  '/game': typeof _layoutGameRoute
  '/insights': typeof _layoutInsightsRoute
  '/search': typeof _layoutSearchRoute
  '/': typeof _layoutIndexRoute
  '/$userName': typeof _layoutUserName_layoutIndexRoute
  '/activyty': typeof _layoutActivytyIndexRoute
  '/$userName/post/$postId': typeof _layoutUserNamePostPostIdRoute
  '/activyty/follows': typeof _layoutActivytyFollowsIndexRoute
  '/$userName/media': typeof _layoutUserName_layoutMediaIndexRoute
  '/$userName/replies': typeof _layoutUserName_layoutRepliesIndexRoute
  '/$userName/reposts': typeof _layoutUserName_layoutRepostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__layout': typeof _layoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/__layout/about': typeof _layoutAboutRoute
  '/__layout/chat': typeof _layoutChatRoute
  '/__layout/game': typeof _layoutGameRoute
  '/__layout/insights': typeof _layoutInsightsRoute
  '/__layout/search': typeof _layoutSearchRoute
  '/__layout/': typeof _layoutIndexRoute
  '/__layout/$userName': typeof _layoutUserNameRouteWithChildren
  '/__layout/$userName/__layout': typeof _layoutUserName_layoutRouteWithChildren
  '/__layout/activyty/': typeof _layoutActivytyIndexRoute
  '/__layout/$userName/post/$postId': typeof _layoutUserNamePostPostIdRoute
  '/__layout/$userName/__layout/': typeof _layoutUserName_layoutIndexRoute
  '/__layout/activyty/follows/': typeof _layoutActivytyFollowsIndexRoute
  '/__layout/$userName/__layout/media/': typeof _layoutUserName_layoutMediaIndexRoute
  '/__layout/$userName/__layout/replies/': typeof _layoutUserName_layoutRepliesIndexRoute
  '/__layout/$userName/__layout/reposts/': typeof _layoutUserName_layoutRepostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/about'
    | '/chat'
    | '/game'
    | '/insights'
    | '/search'
    | '/'
    | '/$userName'
    | '/activyty'
    | '/$userName/post/$postId'
    | '/$userName/'
    | '/activyty/follows'
    | '/$userName/media'
    | '/$userName/replies'
    | '/$userName/reposts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/about'
    | '/chat'
    | '/game'
    | '/insights'
    | '/search'
    | '/'
    | '/$userName'
    | '/activyty'
    | '/$userName/post/$postId'
    | '/activyty/follows'
    | '/$userName/media'
    | '/$userName/replies'
    | '/$userName/reposts'
  id:
    | '__root__'
    | '/__layout'
    | '/auth'
    | '/__layout/about'
    | '/__layout/chat'
    | '/__layout/game'
    | '/__layout/insights'
    | '/__layout/search'
    | '/__layout/'
    | '/__layout/$userName'
    | '/__layout/$userName/__layout'
    | '/__layout/activyty/'
    | '/__layout/$userName/post/$postId'
    | '/__layout/$userName/__layout/'
    | '/__layout/activyty/follows/'
    | '/__layout/$userName/__layout/media/'
    | '/__layout/$userName/__layout/replies/'
    | '/__layout/$userName/__layout/reposts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _layoutRoute: typeof _layoutRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout': {
      id: '/__layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout/$userName': {
      id: '/__layout/$userName'
      path: '/$userName'
      fullPath: '/$userName'
      preLoaderRoute: typeof _layoutUserNameRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/': {
      id: '/__layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _layoutIndexRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/search': {
      id: '/__layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof _layoutSearchRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/insights': {
      id: '/__layout/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof _layoutInsightsRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/game': {
      id: '/__layout/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof _layoutGameRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/chat': {
      id: '/__layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof _layoutChatRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/about': {
      id: '/__layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof _layoutAboutRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/activyty/': {
      id: '/__layout/activyty/'
      path: '/activyty'
      fullPath: '/activyty'
      preLoaderRoute: typeof _layoutActivytyIndexRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/$userName/__layout': {
      id: '/__layout/$userName/__layout'
      path: '/$userName'
      fullPath: '/$userName'
      preLoaderRoute: typeof _layoutUserName_layoutRouteImport
      parentRoute: typeof _layoutUserNameRoute
    }
    '/__layout/activyty/follows/': {
      id: '/__layout/activyty/follows/'
      path: '/activyty/follows'
      fullPath: '/activyty/follows'
      preLoaderRoute: typeof _layoutActivytyFollowsIndexRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/$userName/__layout/': {
      id: '/__layout/$userName/__layout/'
      path: '/'
      fullPath: '/$userName/'
      preLoaderRoute: typeof _layoutUserName_layoutIndexRouteImport
      parentRoute: typeof _layoutUserName_layoutRoute
    }
    '/__layout/$userName/post/$postId': {
      id: '/__layout/$userName/post/$postId'
      path: '/post/$postId'
      fullPath: '/$userName/post/$postId'
      preLoaderRoute: typeof _layoutUserNamePostPostIdRouteImport
      parentRoute: typeof _layoutUserNameRoute
    }
    '/__layout/$userName/__layout/reposts/': {
      id: '/__layout/$userName/__layout/reposts/'
      path: '/reposts'
      fullPath: '/$userName/reposts'
      preLoaderRoute: typeof _layoutUserName_layoutRepostsIndexRouteImport
      parentRoute: typeof _layoutUserName_layoutRoute
    }
    '/__layout/$userName/__layout/replies/': {
      id: '/__layout/$userName/__layout/replies/'
      path: '/replies'
      fullPath: '/$userName/replies'
      preLoaderRoute: typeof _layoutUserName_layoutRepliesIndexRouteImport
      parentRoute: typeof _layoutUserName_layoutRoute
    }
    '/__layout/$userName/__layout/media/': {
      id: '/__layout/$userName/__layout/media/'
      path: '/media'
      fullPath: '/$userName/media'
      preLoaderRoute: typeof _layoutUserName_layoutMediaIndexRouteImport
      parentRoute: typeof _layoutUserName_layoutRoute
    }
  }
}

interface _layoutUserName_layoutRouteChildren {
  _layoutUserName_layoutIndexRoute: typeof _layoutUserName_layoutIndexRoute
  _layoutUserName_layoutMediaIndexRoute: typeof _layoutUserName_layoutMediaIndexRoute
  _layoutUserName_layoutRepliesIndexRoute: typeof _layoutUserName_layoutRepliesIndexRoute
  _layoutUserName_layoutRepostsIndexRoute: typeof _layoutUserName_layoutRepostsIndexRoute
}

const _layoutUserName_layoutRouteChildren: _layoutUserName_layoutRouteChildren =
  {
    _layoutUserName_layoutIndexRoute: _layoutUserName_layoutIndexRoute,
    _layoutUserName_layoutMediaIndexRoute:
      _layoutUserName_layoutMediaIndexRoute,
    _layoutUserName_layoutRepliesIndexRoute:
      _layoutUserName_layoutRepliesIndexRoute,
    _layoutUserName_layoutRepostsIndexRoute:
      _layoutUserName_layoutRepostsIndexRoute,
  }

const _layoutUserName_layoutRouteWithChildren =
  _layoutUserName_layoutRoute._addFileChildren(
    _layoutUserName_layoutRouteChildren,
  )

interface _layoutUserNameRouteChildren {
  _layoutUserName_layoutRoute: typeof _layoutUserName_layoutRouteWithChildren
  _layoutUserNamePostPostIdRoute: typeof _layoutUserNamePostPostIdRoute
}

const _layoutUserNameRouteChildren: _layoutUserNameRouteChildren = {
  _layoutUserName_layoutRoute: _layoutUserName_layoutRouteWithChildren,
  _layoutUserNamePostPostIdRoute: _layoutUserNamePostPostIdRoute,
}

const _layoutUserNameRouteWithChildren = _layoutUserNameRoute._addFileChildren(
  _layoutUserNameRouteChildren,
)

interface _layoutRouteChildren {
  _layoutAboutRoute: typeof _layoutAboutRoute
  _layoutChatRoute: typeof _layoutChatRoute
  _layoutGameRoute: typeof _layoutGameRoute
  _layoutInsightsRoute: typeof _layoutInsightsRoute
  _layoutSearchRoute: typeof _layoutSearchRoute
  _layoutIndexRoute: typeof _layoutIndexRoute
  _layoutUserNameRoute: typeof _layoutUserNameRouteWithChildren
  _layoutActivytyIndexRoute: typeof _layoutActivytyIndexRoute
  _layoutActivytyFollowsIndexRoute: typeof _layoutActivytyFollowsIndexRoute
}

const _layoutRouteChildren: _layoutRouteChildren = {
  _layoutAboutRoute: _layoutAboutRoute,
  _layoutChatRoute: _layoutChatRoute,
  _layoutGameRoute: _layoutGameRoute,
  _layoutInsightsRoute: _layoutInsightsRoute,
  _layoutSearchRoute: _layoutSearchRoute,
  _layoutIndexRoute: _layoutIndexRoute,
  _layoutUserNameRoute: _layoutUserNameRouteWithChildren,
  _layoutActivytyIndexRoute: _layoutActivytyIndexRoute,
  _layoutActivytyFollowsIndexRoute: _layoutActivytyFollowsIndexRoute,
}

const _layoutRouteWithChildren =
  _layoutRoute._addFileChildren(_layoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _layoutRoute: _layoutRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
