/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _layoutRouteImport } from './routes/__layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as _layoutGameRouteImport } from './routes/__layout/game'
import { Route as _layoutAboutRouteImport } from './routes/__layout/about'

const _layoutRoute = _layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutGameRoute = _layoutGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutAboutRoute = _layoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => _layoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof _layoutAboutRoute
  '/game': typeof _layoutGameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof _layoutAboutRoute
  '/game': typeof _layoutGameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__layout': typeof _layoutRouteWithChildren
  '/__layout/about': typeof _layoutAboutRoute
  '/__layout/game': typeof _layoutGameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/game'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/game'
  id: '__root__' | '/' | '/__layout' | '/__layout/about' | '/__layout/game'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _layoutRoute: typeof _layoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__layout': {
      id: '/__layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout/game': {
      id: '/__layout/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof _layoutGameRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/about': {
      id: '/__layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof _layoutAboutRouteImport
      parentRoute: typeof _layoutRoute
    }
  }
}

interface _layoutRouteChildren {
  _layoutAboutRoute: typeof _layoutAboutRoute
  _layoutGameRoute: typeof _layoutGameRoute
}

const _layoutRouteChildren: _layoutRouteChildren = {
  _layoutAboutRoute: _layoutAboutRoute,
  _layoutGameRoute: _layoutGameRoute,
}

const _layoutRouteWithChildren =
  _layoutRoute._addFileChildren(_layoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _layoutRoute: _layoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
